color0 #41474d
color1 #ffb4ab
color2 #96cdf8
color3 #b7c9d9
color4 #cfc0e8
color5 #96cdf8
color6 #b7c9d9
color7 #e0e3e8
color8 #8b9198
color9 #ffb4ab
color10 #96cdf8
color11 #b7c9d9
color12 #cfc0e8
color13 #96cdf8
color14 #b7c9d9
color15 #e0e3e8

cursor                #e0e3e8
cursor_text_color     #101417
background            #101417
foreground            #e0e3e8
selection_foreground  #c1c7ce
selection_background  #41474d
active_border_color   #96cdf8
inactive_border_color #41474d
url_color             #96cdf8

active_tab_foreground   #00344e
active_tab_background   #96cdf8
inactive_tab_foreground #c1c7ce
inactive_tab_background #41474d
cursor_trail_color      #c1c7ce
