color0 #494550
color1 #ffb4ab
color2 #cebdff
color3 #ccc1e4
color4 #ffaed8
color5 #cebdff
color6 #ccc1e4
color7 #e6e1e7
color8 #948f9b
color9 #ffb4ab
color10 #cebdff
color11 #ccc1e4
color12 #ffaed8
color13 #cebdff
color14 #ccc1e4
color15 #e6e1e7

cursor                #e6e1e7
cursor_text_color     #141317
background            #141317
foreground            #e6e1e7
selection_foreground  #cac4d1
selection_background  #494550
active_border_color   #cebdff
inactive_border_color #494550
url_color             #cebdff

active_tab_foreground   #362367
active_tab_background   #cebdff
inactive_tab_foreground #cac4d1
inactive_tab_background #494550
cursor_trail_color      #cac4d1
