tab_bar_style powerline
tab_bar_edge    top

background_opacity 0.95
font_family Source Code Pro Semibold

italic_font      auto
bold_font        true
bold_italic_font auto

font_size        10

shell_integration no-cursor
cursor_shape block
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

scrollback_lines 10000

scrollback_pager less +G -R

wheel_scroll_multiplier 5.0

click_interval 0.5

select_by_word_characters :@-./_~?&=%+#

mouse_hide_wait 0.0

#enabled_layouts *

remember_window_size   no
initial_window_width   640
initial_window_height  400

repaint_delay    10

input_delay 3

visual_bell_duration 0.0

enable_audio_bell yes

open_url_with default

term xterm-kitty

window_border_width 0
window_margin_width 15


# Key mapping
# For a list of key names, see: http://www.glfw.org/docs/latest/group__keys.html
# For a list of modifier names, see: http://www.glfw.org/docs/latest/group__mods.html
# You can use the special action no_op to unmap a keyboard shortcut that is
# assigned in the default configuration.

# Clipboard
map super+v             paste_from_clipboard
map ctrl+shift+s        paste_from_selection
map super+c             copy_to_clipboard
map shift+insert        paste_from_selection

# Scrolling
map ctrl+shift+up        scroll_line_up
map ctrl+shift+down      scroll_line_down
map ctrl+shift+k         scroll_line_up
map ctrl+shift+j         scroll_line_down
map ctrl+shift+page_up   scroll_page_up
map ctrl+shift+page_down scroll_page_down
map ctrl+shift+home      scroll_home
map ctrl+shift+end       scroll_end
map ctrl+shift+h         show_scrollback

# Window management
map super+n             new_os_window
map super+w             close_window
map ctrl+shift+enter    new_window
map ctrl+shift+]        next_window
map ctrl+shift+[        previous_window
map ctrl+shift+f        move_window_forward
map ctrl+shift+b        move_window_backward
map alt+`        move_window_to_top
map alt+1        first_window
map alt+2        second_window
map alt+3        third_window
map alt+4        fourth_window
map alt+5        fifth_window
map alt+6        sixth_window
map alt+7        seventh_window
map alt+8        eighth_window
map alt+9        ninth_window
map alt+0        tenth_window
map alt+t 		 new_tab

# Tab management
map ctrl+shift+right    next_tab
map ctrl+shift+left     previous_tab
map ctrl+shift+t        new_tab
map ctrl+shift+q        close_tab
map ctrl+shift+l        next_layout
map ctrl+shift+.        move_tab_forward
map ctrl+shift+,        move_tab_backward

# Miscellaneous
map ctrl+shift+up      increase_font_size
map ctrl+shift+down    decrease_font_size
map ctrl+shift+backspace restore_font_size

hide_window_decorations titlebar-only
allow_remote_control yes


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
